# tabac #

import
  xam

const
  C_EXTENSION* = STRINGS_PERIOD & STRINGS_LOWERCASE_C
  H_EXTENSION* = STRINGS_PERIOD & STRINGS_LOWERCASE_H
  C_LANGUAGE*: tuple = (
    LINE_COMMENT: STRINGS_SLASH & STRINGS_SLASH,
    MULTILINE_COMMENT_OPEN: STRINGS_SLASH & STRINGS_ASTERISK,
    MULTILINE_COMMENT_CLOSE: STRINGS_ASTERISK & STRINGS_SLASH,
    STATIC_KEYWORD: "static",
    CONST_KEYWORD: "const",
    TYPEDEF_KEYWORD: "typedef",
    STRUCT_KEYWORD: "struct",
    UNION_KEYWORD: "union",
    ENUM_KEYWORD: "enum",
    IF_KEYWORD: "if",
    ELSE_KEYWORD: "else",
    DO_KEYWORD: "do",
    WHILE_KEYWORD: "while",
    SWITCH_KEYWORD: "switch",
    MS_TRY: "__try",
    MS_EXCEPT: "__except",
    MS_FINALLY: "__finally"
  )
  # transformation
  C_SELF_CLOSING_EMPTY_STRUCTURES* = [
    C_LANGUAGE.STRUCT_KEYWORD, C_LANGUAGE.UNION_KEYWORD, C_LANGUAGE.ENUM_KEYWORD,
    C_LANGUAGE.IF_KEYWORD, C_LANGUAGE.ELSE_KEYWORD, C_LANGUAGE.DO_KEYWORD
  ]
  C_CLOSING_SEMICOLON_STRUCTURES* = [
    C_LANGUAGE.STRUCT_KEYWORD, C_LANGUAGE.UNION_KEYWORD, C_LANGUAGE.ENUM_KEYWORD
  ]
  # validation
  C_VALID_LAST_CHARS* = [
    CHARS_PARENTHESES_CLOSE, CHARS_COMMA, CHARS_SEMICOLON, CHARS_COLON, CHARS_BACKSLASH, CHARS_EQUAL
  ]
  C_VALID_SINGLE_KEYWORDS* = [
    C_LANGUAGE.DO_KEYWORD, C_LANGUAGE.ELSE_KEYWORD
  ]
  C_VALID_LINE_STARTS* = [
    C_LANGUAGE.STRUCT_KEYWORD, C_LANGUAGE.UNION_KEYWORD, C_LANGUAGE.ENUM_KEYWORD,
    C_LANGUAGE.TYPEDEF_KEYWORD, C_LANGUAGE.STATIC_KEYWORD, C_LANGUAGE.CONST_KEYWORD,
    C_LANGUAGE.MS_TRY, C_LANGUAGE.MS_EXCEPT, C_LANGUAGE.MS_FINALLY
  ]

